version: '2'

services:
   fastrweb:
     image: johanneselias/fastrweb:1.4
     container_name: fastr
     volumes: 
       - ./import:/setup/sites
     ports:
       - "80:80"
       - "8080:8080"
     restart: always

