version: '2'

services:
   fastrweb:
     image: johanneselias/fastrweb
     container_name: fastr
     volumes: 
       - ./R:/var/FastRWeb/web.R
       - ./php:/var/www/html
     ports:
       - "80:80"
     restart: always

